### ISSUE TITLE
Show/Hide button misbehaving on simultaneous click

### ISSUE THREAD

**Issue by Sathrya** [atapas/react-add-table-dynamic-row#1]
When clicked on show button on two different rows the earlier clicked button label changes to "Show" where as the button should stay as "Hide"

**Comment by Sathrya** [comment]
![IMG20220207175312](https://user-images.githubusercontent.com/53817045/152787507-36eaabba-95a5-4dfe-a0a1-a6b356dd7423.jpg)
As you can see when simultaneously expanded the label is changed to show

**Comment by Sathrya** [comment]
declare another state variable for toggling between show and hide:
       const [showHide,setShowHide] = useState([]);
And instead of below code:
         let obj={};
        isRowExpanded ? (obj[index]=false) : (obj[index]=true);
        console.log("State"+JSON.stringify(obj))
        this.setState({
        expandedRegistrationState:obj
       });
Add:
    let obj=this.state.showArray
    e.target.innerText == 'Show'? (obj.push(index),this.setState({showArray:obj})) : 
                                       (obj.splice(obj.indexOf(index),1),this.setState({showArray:obj}))

This will resolve the problem

**Comment by atapas** [comment]
> declare another state variable for toggling between show and hide: const [showHide,setShowHide] = useState([]); And instead of below code: let obj={}; isRowExpanded ? (obj[index]=false) : (obj[index]=true); console.log("State"+JSON.stringify(obj)) this.setState({ expandedRegistrationState:obj }); Add: let obj=this.state.showArray e.target.innerText == 'Show'? (obj.push(index),this.setState({showArray:obj})) : (obj.splice(obj.indexOf(index),1),this.setState({showArray:obj}))
> 
> This will resolve the problem

Just raise a PR with the code changes. I shall review and take care.
